# Generated by Django 5.0.1 on 2024-03-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('done', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
